on: push
jobs:
    scratch-org-test:
        runs-on: ubuntu-latest
        steps:
            #1. Checkout the source code for identifying changes
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

            #2 Get Added or Changed files
            - name: 'Get added or changed from the currect changeset files'
              uses: tj-actions/changed-files@v39
              id: changed-files

            #3 set all the Added or Changed files into a internal veriable 'CHANGED_FILES'
            - name: 'Echo Added or Changed files'
              id: ConsolidatedChangedFiles
              run: |
                varcnt=1
                for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
                  if [[ $file != *"yml"* ]]; then
                    if [[ $varcnt == 2 ]]; then
                      res="${res} ${file}"
                      echo $res
                    fi
                    if [[ $varcnt == 1 ]]; then
                      res = ${file}
                      echo $res
                      varcnt = 2
                    fi
                  fi
                done
                #echo ::set-output name=CHANGED_FILES:: $res 
                echo "CHANGED_FILES=$res" >> $GITHUB_OUTPUT

            - name: 'Test Changed File List'
              run: |
                echo ${{steps.ConsolidatedChangedFiles.outputs.CHANGED_FILES}}
                #echo $changedFiles