on: push
jobs:
    scratch-org-test:
        runs-on: ubuntu-latest
        steps:
            # Checkout the source code
            - name: 'Checkout source code'
              uses: actions/checkout@v4

            # Install Salesforce CLI
            - name: 'Install Salesforce CLI'
              run: |
                wget https://developer.salesforce.com/media/salesforce-cli/sf/channels/stable/sf-linux-x64.tar.xz
                mkdir ~/sf
                tar xJf sf-linux-x64.tar.xz -C ~/sf --strip-components 1
                echo "$HOME/sf/bin" >> $GITHUB_PATH
                ~/sf/bin/sf version

            #Get Added or Changed files
            - name: 'Get Added or Changed files'
              uses: tj-actions/changed-files@v39
              id: changed-files
              with: 
                files: |
                  *.cls
                  *.test.cls
                  *.Test.cls

            #Display all the Added or Changed files
            - name: 'Echo Added or Changed files'
              run: |
                echo "${{ steps.changed-files.outputs.all_changed_files }}"
