on: push
jobs:
    scratch-org-test:
        runs-on: ubuntu-latest
        steps:
            #1. Checkout the source code for identifying changes
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

            #2 Get Added or Changed files
            - name: 'Get added or changed from the currect changeset files'
              uses: tj-actions/changed-files@v39
              id: changed-files

            #3 set all the Added or Changed files into a internal veriable 'CHANGED_FILES'
            #Note: In the veriable assignment statement there should be no spaces between the variable name the equals operator and the value
            - name: 'Echo Added or Changed files'
              id: ConsolidatedChangedFiles
              shell: bash
              run: |
                res=""
                for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
                  if [[ $file != *"yml"* ]]; then
                    if [[ -z "$res" ]]; then
                      res="${res} ${file}"
                      echo $res
                    else
                      res=$file
                      echo $res
                    fi
                  fi
                done
                echo "CHANGED_FILES=$res" >> $GITHUB_OUTPUT

            - name: 'Test Changed File List'
              run: |
                changedFiles="${{steps.ConsolidatedChangedFiles.outputs.CHANGED_FILES}}"
                echo $changedFiles